networks:
    network:
        driver: bridge
    proxy-network:
        driver: bridge  # sieć dla proxy i aplikacji

volumes:
    db_data:

services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./task:/var/www
        environment:
            - APP_ENV=dev
            - DATABASE_URL=pgsql://user:passwd@db:5432/db
        depends_on:
            - db
        networks:
            - network
            - proxy-network   # dodajemy sieć proxy

    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./task:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - network
            - proxy-network   # dodajemy sieć proxy

    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: passwd
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql
        networks:
            - network

    nginx-proxy:
        image: nginx:latest
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - "80:80"    # host port 80 → proxy
        volumes:
            - ./proxy/conf.d:/etc/nginx/conf.d:ro
        networks:
            - proxy-network   # tylko sieć proxy
